### ISSUE TITLE
are you ok?

### ISSUE THREAD

**Issue by stuffbymax** [ModelCitizenPS3/ps3linux-hugo-website#2]

**Comment by ModelCitizenPS3** [comment]
more or less, lol

**Comment by stuffbymax** [comment]
do you know how to make ftp server

**Comment by ModelCitizenPS3** [comment]
coding an ftp server from scratch is a bit above my skill currently; all I know about FTP is that it uses 2 network ports, one for data and one for control signals. ftp server actually sounds like a perfect project to help learn networking & filesystem APIs though, so cool idea! what language would you use? Recently I've been getting back into C/C++ (mostly cuz of a class I'm taking now).  
Hey guess what! I forked a PS3 (CELL) crypto miner (Litecoin) written in C and I've been studying the code. Its 14 years old, so needs some updates - may need to upgrade SSL/TLS implementations. Could be fun. Going to talk about it on my next stream - maybe today :-)

**Comment by stuffbymax** [comment]
technically me python because my course i want to create fpt server to connect 2 laptops and share files

**Comment by stuffbymax** [comment]
when i boot to petiboot it will shout down the ps3 is it becasuse i dont have a disto on usb?
